# Generated by Django 5.2.1 on 2025-05-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, verbose_name="Libellé d'entrée")),
                ('dateEntree', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée',
                'verbose_name_plural': 'Entées',
                'db_table': 't_Entree',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSortie', models.DateField(auto_now_add=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé de sortie')),
            ],
            options={
                'verbose_name': 'SortieStock',
                'verbose_name_plural': 'SortieStocks',
                'db_table': 't_SortieStock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntreeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.entree')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'DetailAppro',
                'verbose_name_plural': 'DetailAppros',
                'db_table': 't_DetailAppro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SortieItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('motif', models.TextField(verbose_name='Motif de sortie')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sortiestock')),
            ],
            options={
                'verbose_name': 'DetailSortie',
                'verbose_name_plural': 'DetailSorties',
                'db_table': 't_DetailSortie',
                'managed': True,
            },
        ),
    ]
