# Generated by Django 5.2.1 on 2025-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniteVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=250, unique=True, verbose_name='Unité')),
                ('unitTag', models.CharField(max_length=3, unique=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date de creation')),
                ('status', models.CharField(choices=[('Activée', 'Activée'), ('Désactivée', 'Désactivée')], default='Activée', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'UniteVente',
                'verbose_name_plural': 'UniteVentes',
                'db_table': 't_UniteVente',
                'managed': True,
            },
        ),
    ]
