# Generated by Django 5.2.1 on 2025-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Activé', 'Activé'), ('Désactivé', 'Désactivé'), ('Expiré', 'Expiré'), ('Supprimé', 'Supprimé')], default='Activé', max_length=10, verbose_name='Statut'),
        ),
    ]
