# Generated by Django 5.2.1 on 2025-06-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': "Date d'expiration",
                'verbose_name_plural': "Dates d'expiration",
                'db_table': 't_DateExpiration',
                'managed': True,
            },
        ),
    ]
