# Generated by Django 5.2.1 on 2025-05-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAbsences', models.IntegerField(default=0)),
                ('penaliteAbsences', models.IntegerField(default=0)),
                ('totalCredit', models.IntegerField(default=0)),
                ('totalRetenu', models.IntegerField(default=0)),
                ('netApayer', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fiche_paie',
                'verbose_name_plural': 'Fiche_paies',
                'db_table': 't_Fiche_paie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('estPaye', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paie',
                'verbose_name_plural': 'Paies',
                'db_table': 't_Paie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('postnom', models.CharField(max_length=255, verbose_name='Post-nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('fonction', models.CharField(choices=[('Gérant', 'Gerant'), ('Caissier', 'Caissier'), ('Admin', 'Admin')], default='Caissier', max_length=255, verbose_name='Fonction')),
                ('salaire', models.IntegerField(verbose_name='Salaire')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('Engagé', 'Engage'), ('Démissionné', 'Demissionne'), ('Licencié', 'Licencie')], default='Engagé', max_length=100, verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(default=0)),
                ('fichePaie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.fichepaie')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'db_table': 't_Absence',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fichepaie',
            name='paie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.paie'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField(default=0)),
                ('paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.paie')),
            ],
        ),
    ]
