# Generated by Django 5.2.1 on 2025-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='status',
            field=models.CharField(choices=[('Activée', 'Activée'), ('Désactivée', 'Désactivée'), ('Supprimée', 'Supprimée')], default='Activée', max_length=10, verbose_name='Status'),
        ),
    ]
