# Generated by Django 5.2.1 on 2025-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compony_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entréprise")),
                ('compony_slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name="Slogan de l'entréprise")),
                ('compony_rccm', models.CharField(blank=True, max_length=255, null=True, verbose_name="N° RCCM de l'entréprise")),
                ('compony_idnat', models.CharField(blank=True, max_length=255, null=True, verbose_name="ID Nat de l'entréprise")),
                ('compony_country', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'entréprise")),
                ('compony_city', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'entréprise")),
                ('compony_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name="Téléphone de l'entréprise")),
                ('compony_email', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse mail de l'entréprise")),
                ('compony_province', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'entréprise")),
                ('compony_adress', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'entréprise")),
                ('taux', models.PositiveSmallIntegerField(blank=True, default=2800, null=True, verbose_name='Taux de change')),
                ('remise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Remise sur vente')),
                ('seuil_remise', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Somme min. à beneficier de la remise ')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
