# Generated by Django 5.2.1 on 2025-05-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dollar', models.PositiveBigIntegerField()),
                ('franc', models.PositiveBigIntegerField()),
                ('estConfirme', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cash',
                'verbose_name_plural': 'Cash',
                'db_table': 't_Cash',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntreeCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dollar', models.PositiveBigIntegerField()),
                ('franc', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=255, verbose_name='Déscription')),
                ('estConfirme', models.BooleanField(default=False)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.cash')),
            ],
            options={
                'verbose_name': 'Entree_stock',
                'verbose_name_plural': 'Entree_stocks',
                'db_table': 't_Entree_Stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SortieCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dollar', models.PositiveBigIntegerField()),
                ('franc', models.PositiveBigIntegerField()),
                ('description', models.CharField(max_length=255, verbose_name='Déscription')),
                ('estConfirme', models.BooleanField(default=False)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash.cash')),
            ],
            options={
                'verbose_name': 'Sortie_stock',
                'verbose_name_plural': 'Sortie_stocks',
                'db_table': 't_Sortie_Stock',
                'managed': True,
            },
        ),
    ]
