# Generated by Django 5.2.1 on 2025-05-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreecash',
            options={'managed': True, 'verbose_name': 'Entree_Cash', 'verbose_name_plural': 'Entree_Cash'},
        ),
        migrations.AlterModelOptions(
            name='sortiecash',
            options={'managed': True, 'verbose_name': 'Sortie_Cash', 'verbose_name_plural': 'Sortie_Cash'},
        ),
        migrations.AlterModelTable(
            name='entreecash',
            table='t_Entree_Cash',
        ),
        migrations.AlterModelTable(
            name='sortiecash',
            table='t_Sortie_Cash',
        ),
    ]
