# Generated by Django 5.2.1 on 2025-05-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_entreecash_options_alter_sortiecash_options_and_more'),
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vente.session', verbose_name='Session'),
            preserve_default=False,
        ),
    ]
