# Generated by Django 5.2.1 on 2025-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UIa333e2yY4oQUvYFnwA87XMBC94pMNr', editable=False, max_length=32, unique=True),
        ),
    ]
