# Generated by Django 5.2.1 on 2025-05-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='I2jIFQqeAGotFCgNp227SENbjdO7G1uL', editable=False, max_length=32, unique=True),
        ),
    ]
