# Generated by Django 5.2.1 on 2025-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ZF2S8HLYYOidVUJ4oZiHnG9JRpqJ496s', editable=False, max_length=32, unique=True),
        ),
    ]
