# Generated by Django 5.2.1 on 2025-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='s28iNmCklqWFwNQF6uHy362ZfG1eIaTJ', editable=False, max_length=32, unique=True),
        ),
    ]
