# Generated by Django 5.2.1 on 2025-05-09 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFacture', models.CharField(max_length=15, verbose_name='N° Facture')),
                ('dateFacture', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('remise', models.IntegerField(default=0)),
                ('netPaye', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 't_Facture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NumFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastNum', models.SmallIntegerField(default=0, verbose_name='Dernier Numéro de Facture')),
            ],
            options={
                'verbose_name': 'NumFacture',
                'verbose_name_plural': 'NumFactures',
                'db_table': 't_NumFacture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateField()),
                ('total', models.IntegerField(default=0)),
                ('total_franc', models.IntegerField(default=0)),
                ('total_dollar', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 't_Vente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('prix', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 't_Cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('prix', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'LigneFacture',
                'verbose_name_plural': 'LigneFactures',
                'db_table': 't_LigneFacture',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='product',
            field=models.ManyToManyField(related_name='Product_fact_Items', through='vente.LigneFacture', to='product.product'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstOuvert', models.BooleanField(default=False)),
                ('LastDateOpen', models.DateTimeField(blank=True, null=True)),
                ('LastDateClose', models.DateTimeField(blank=True, null=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 't_Session',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.session'),
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.vente'),
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de dépense')),
                ('montant_franc', models.IntegerField()),
                ('montant_dollar', models.IntegerField()),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.vente')),
            ],
            options={
                'verbose_name': 'Depense',
                'verbose_name_plural': 'Depenses',
                'db_table': 't_Depense',
                'managed': True,
            },
        ),
    ]
