# Generated by Django 5.2.1 on 2025-06-08 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numfacture',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 8)),
            preserve_default=False,
        ),
    ]
